"""rename department

Revision ID: 0b56a6db5d8d
Revises: 1af92e668b1c
Create Date: 2025-06-14 04:00:37.095827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b56a6db5d8d'
down_revision = '1af92e668b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
