"""rename department 2

Revision ID: 4bcad0a3028d
Revises: 727c4010430d
Create Date: 2025-06-14 04:20:15.601360

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4bcad0a3028d"
down_revision = "727c4010430d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "departmentss")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departmentss", "department")
    # ### end Alembic commands ###
