"""rename from location to address

Revision ID: 7540582a816b
Revises: e84cadcc19e5
Create Date: 2025-06-14 04:30:46.258181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7540582a816b'
down_revision = 'e84cadcc19e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    # op.drop_column('departments', 'location')
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'address')
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###
