"""rename department second time

Revision ID: e84cadcc19e5
Revises: 4bcad0a3028d
Create Date: 2025-06-14 04:26:12.651331

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e84cadcc19e5"
down_revision = "4bcad0a3028d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departmentss", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "departmentss")
    # ### end Alembic commands ###
